## currency
+ currency: USD (string) - 3-character ISO code that indicates the currency in which you want to retrieve monetary amounts. The API calculates the amount equivalents and returns the amounts in the currency specified. For example, if the `currency` field value is set to `USD`, then the room rate, discount, taxes, and other monetary amounts are returned in their `USD` amount equivalents. We support all <a target="_blank" href="../reference-reads#currencies">ISO currencies</a>. If you want to configure multiple currencies, please contact cxLoyalty Business Team.<br><br>Consider a scenario where you set the `currency` field value to `USD` and the supplier's currency is in `AUD`. The API calculates the `AUD` to `USD` amount equivalents and displays monetary amounts in `USD`.<br><br>
<b>Note:</b> If you do not provide the `currency` field, the `currency` field value will automatically be set based on the default account configuration.
