## initiateSearchRadial
+ include currency
+ include searchQueryRadial 
+ include user
+ include programId

## session (object)
+ sessionId: `0f8fad5b-d9cb-461f-a165-70867728951z` (string) - Unique acknowledgement token that indicates that the request has been received and the processing has been initiated. You must use this `sessionId` for further calls in the same session. The session ID is valid for 60 minutes from the time it is generated.
