## searchQueryRadial
+ searchQuery (searchQueryRadialInfo, required) - Contains the list of search criteria that must be used to search for hotels. The `searchQuery` object must contain the <@ roomoccupancy @> details, the <@ stayperiod @>, and the information about the region where the <@ customer_popup @> wants to search for the hotels.
