# Data Structures

## stayPeriod 
+ start: `{dateTime|YYYY-MM-DDTHH:mm:ssZ|30 0}` (string, required) - Check-in date or the start date of the stay duration.<br><br><b>Format:</b> YYYY-MM-DD or or YYYY-MM-DDTHH:MM:SSZ<br><br><a href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601</a>
+ end: `{dateTime|YYYY-MM-DDTHH:mm:ssZ|33 0}` (string, required) - Check-out date or the end date of the stay duration.<br><br><b>Format:</b> YYYY-MM-DD or YYYY-MM-DDTHH:MM:SSZ<br><br><a href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601</a>
